# Generated by Django 3.2.12 on 2023-11-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='log_path',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='log_text',
            field=models.TextField(null=True),
        ),
    ]
